version: "3.1"
services:
    wireguard-client:
        build: .
        container_name: wireguard-client
        cap_add: 
            - NET_ADMIN 
        volumes: 
            - "/etc/wireguard:/etc/wireguard"